### ISSUE TITLE
Increase maximum upload size to 60MB

### ISSUE THREAD

**Issue by seabilwe** [kartoza/training.kartoza.com#3]
The current maximum upload size on the training platform is 40MB. To accommodate upcoming courses with larger uploads exceeding 40MB, we need this limit to be increased to 60MB.
![image](https://github.com/kartoza/training.kartoza.com/assets/56301949/abd71079-63c9-44cc-82bf-f772b06646c6)

cc @gubuntu

**Comment by tharanathkartoza** [comment]
@seabilwe I have increased the limit. Please have a look.

**Comment by seabilwe** [comment]
@tharanathkartoza Thank you 
![image](https://github.com/kartoza/training.kartoza.com/assets/56301949/1dfb36fd-d692-458e-b26e-6b63e95b33c2)
